import { useState } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes } from 'react-router-dom'
import './App.css'

const products = [
  { name: 'Organic Coffee Scrub', type: 'Exfoliating body treatment', price: '$28.00', image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=900&q=85', featured: true },
  { name: 'Velvet Body Oil', type: 'Nourishing botanical oil', price: '$34.00', image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=85' },
  { name: 'Cloud Cleanse', type: 'Gentle daily wash', price: '$22.00', image: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?auto=format&fit=crop&w=900&q=85' },
]

function Mark({ name = 'spark' }) {
  const paths = { arrow: 'M5 12h14M13 6l6 6-6 6', menu: 'M4 7h16M4 12h16M4 17h16', close: 'M6 6l12 12M18 6 6 18', instagram: 'M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm5 5a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm5.5-.5h.01' }
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]} /></svg>
}

function Layout({ children }) {
  const [open, setOpen] = useState(false)
  const links = [['/', 'Home'], ['/products', 'Products'], ['/about', 'About'], ['/resellers', 'Resellers'], ['/contact', 'Contact']]
  return <div className="site-shell">
    <header className="site-header"><Link to="/" className="wordmark" onClick={() => setOpen(false)}><span>YAMIN</span> THEINT</Link><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Toggle navigation"><Mark name={open ? 'close' : 'menu'} /></button><nav className={open ? 'main-nav is-open' : 'main-nav'}>{links.map(([path, label]) => <NavLink key={path} to={path} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}>{label}</NavLink>)}</nav><Link to="/contact" className="header-cta">Find your ritual <Mark name="arrow" /></Link></header>
    <main>{children}</main>
    <footer className="site-footer"><div className="footer-top"><Link to="/" className="wordmark"><span>YAMIN</span> THEINT</Link><p>Beauty, distilled to its purest form.</p><div className="footer-social"><a href="https://instagram.com" aria-label="Instagram"><Mark name="instagram" /></a><a href="mailto:hello@yamintheint.com" aria-label="Email"><Mark name="arrow" /></a></div></div><div className="footer-bottom"><span>Copyright 2026 Yamin Theint</span><span>Yangon, Myanmar</span><a href="mailto:hello@yamintheint.com">hello@yamintheint.com</a></div></footer>
  </div>
}

function Button({ children, to = '/contact', light = false }) { return <Link to={to} className={light ? 'button button-light' : 'button'}>{children}<Mark name="arrow" /></Link> }
function ProductCard({ product }) { return <article className="product-card"><div className="product-image"><img src={product.image} alt={product.name} /><span>{product.featured ? 'Bestseller' : 'New ritual'}</span></div><div className="product-meta"><div><h3>{product.name}</h3><p>{product.type}</p></div><strong>{product.price}</strong></div></article> }
function PageIntro({ eyebrow, title, children }) { return <section className="page-intro"><div className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{children}</section> }

function Home() { return <><section className="hero-banner"><div className="hero-grain" /><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><div className="hero-product"><div className="product-glow" /><div className="product-placeholder"><img src="https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=700&q=85" alt="Arabica coffee beans for Yamin Theint coffee scrub" /><div className="placeholder-shade" /><div className="placeholder-copy"><span>ORGANIC COFFEE</span><small>Arabica body scrub</small></div></div><div className="floating-speck speck-one" /><div className="floating-speck speck-two" /><div className="floating-speck speck-three" /></div><div className="hero-divider"><i /> <span>YAMIN THEINT</span> <i /></div><div className="hero-content"><p className="eyebrow">A ritual born from the earth</p><h1>Nature's Gift<br /><em>for Your Skin</em></h1><p className="hero-intro">A ritual born from the earth — pure Arabica coffee grounds, virgin coconut oil, and precious botanicals, hand-crafted to reveal your skin's natural luminosity.</p><Button to="/products">Discover the ritual</Button></div><div className="hero-scroll">Scroll to explore <span /></div></section><section className="marquee"><span>Plant-powered</span><i>✦</i><span>Conscious beauty</span><i>✦</i><span>Made in Myanmar</span><i>✦</i><span>Plant-powered</span></section><section className="auth-section"><div><p className="eyebrow">A promise in every jar</p><h2>Know what you<br /><em>put on your skin.</em></h2></div><div className="auth-copy"><p>Every Yamin Theint product has a story, a source, and a signature. Check your product's authenticity and discover the care behind your ritual.</p><Button to="/contact" light>Verify your product</Button></div><div className="auth-seal">YT<br /><span>AUTHENTIC</span></div></section><section className="feature-section"><div className="section-heading"><div><p className="eyebrow">The edit</p><h2>Rituals worth<br /><em>returning to.</em></h2></div><Button to="/products" light>View all products</Button></div><div className="product-grid">{products.slice(0, 2).map((product) => <ProductCard key={product.name} product={product} />)}</div></section></> }
function Products() { return <PageIntro eyebrow="The collection" title={<>Body care for<br /><em>slow living.</em></>}><p className="intro-text">A considered edit of sensorial formulas made with generous botanicals, quiet intention, and nothing you do not need.</p><div className="product-grid product-grid-wide">{products.map((product) => <ProductCard key={product.name} product={product} />)}</div><section className="ingredient-note"><div><p className="eyebrow">The Yamin standard</p><h2>Good to skin.<br /><em>Good to earth.</em></h2></div><p>We work with purposeful ingredients and thoughtful packaging, creating products that feel as good in your hands as they do on your skin.</p></section></PageIntro> }
function About() { return <PageIntro eyebrow="Our story" title={<>Beauty with a<br /><em>point of view.</em></>}><div className="story-layout"><img src="https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1000&q=85" alt="Founder of Yamin Theint" /><div className="story-copy"><p className="quote">“The most beautiful rituals are the ones that bring us back to ourselves.”</p><p>Yamin Theint began with a simple belief: care should never feel complicated. Founded in Yangon, our studio creates tactile, effective body care inspired by the plants, textures, and unhurried rhythms of home.</p><p>Each formula is an invitation to pause. To choose a little more intention in the everyday.</p><span className="signature">Yamin Theint<br /><small>Founder and Formulator</small></span></div></div></PageIntro> }
function Resellers() { const people = [['01', 'The Ritual Room', 'Yangon, Bahan', '@theritualroom'], ['02', 'Maison Botanique', 'Mandalay, Chanayethazan', '@maisonbotanique'], ['03', 'Common Ground', 'Yangon, Dagon', '@commonground.mm'], ['04', 'Nourish Studio', 'Naypyidaw, Zabuthiri', '@nourishstudio']]; return <PageIntro eyebrow="Find us" title={<>Shop the ritual<br /><em>in person.</em></>}><p className="intro-text">Our authorized stockists share our belief in slower, more considered beauty. Find your nearest space below.</p><div className="reseller-list">{people.map(([number, name, location, handle]) => <a href="#contact" className="reseller-row" key={name}><span>{number}</span><div><h3>{name}</h3><p>{location}</p></div><span>{handle}</span><Mark name="arrow" /></a>)}</div></PageIntro> }
function Contact() { return <PageIntro eyebrow="Get in touch" title={<>Let's make space<br /><em>for good care.</em></>}><div className="contact-layout"><div><p className="intro-text">Questions about a product, a partnership, or your next ritual? We would love to hear from you.</p><div className="contact-details"><span>Write to us</span><a href="mailto:hello@yamintheint.com">hello@yamintheint.com</a><span>Visit our studio</span><p>Yangon, Myanmar<br />Mon - Sat, 9am - 5pm</p></div></div><form onSubmit={(event) => event.preventDefault()}><label>Name<input type="text" placeholder="Your name" required /></label><label>Email<input type="email" placeholder="you@email.com" required /></label><label>How can we help?<textarea rows="4" placeholder="Tell us a little more..." required /></label><button className="button" type="submit">Send inquiry <Mark name="arrow" /></button></form></div></PageIntro> }

function App() { return <BrowserRouter><Layout><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/about" element={<About />} /><Route path="/resellers" element={<Resellers />} /><Route path="/contact" element={<Contact />} /></Routes></Layout></BrowserRouter> }
export default App